"""
utils.py — Ortak yardımcı fonksiyonlar ve model yükleme
"""

import os
import re
import pickle
import numpy as np
import pandas as pd
import streamlit as st
from pathlib import Path
import torch
SAVE_DIR = Path(__file__).parent / "saved_models"

# ── Leakage regex (notebook ile aynı) ────────────────────────────────────────
LABEL_PATTERNS = [
    r'\(ai[\s\-]?generated\)',
    r'ai[\s\-]?generated',
    r'written by ai',
    r'generated by (ai|gpt|chatgpt|claude|llm)',
    r'this (text|content|essay|article) (was |is )?(ai|artificially)[\s\-]?(generated|written|created)',
    r'as an ai',
    r"i'?m an ai",
    r'large language model',
]
LABEL_RE = re.compile('|'.join(LABEL_PATTERNS), re.IGNORECASE)


def clean_text(text: str) -> str:
    text = LABEL_RE.sub(' ', str(text))
    text = text.lower()
    text = re.sub(r'[^\w\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


@st.cache_resource(show_spinner="Modeller yükleniyor…")
def load_models():
    """saved_models/ klasöründen tüm pkl dosyalarını yükler."""
    required = [
        'mnb_A','mnb_B','mnb_C',
        'mnb_vec_1','mnb_vec_2','mnb_vec_C',
        'xgb_A','xgb_B','xgb_C',
        'tfidf_1','tfidf_2','tfidf_C',
        'all_results',
        'X2_test_text','y2_test',
        'X1_test_text','y1_test',
        'X_comb_test','y_comb_test',
    ]
    missing = [r for r in required if not (SAVE_DIR / f"{r}.pkl").exists()]
    if missing:
        return None, missing

    models = {}
    for name in required:
        path = SAVE_DIR / f"{name}.pkl"
        with open(path, 'rb') as f:
            models[name] = pickle.load(f)

    # df_perf opsiyonel
    perf_path = SAVE_DIR / "df_perf.pkl"
    if perf_path.exists():
        with open(perf_path, 'rb') as f:
            models['df_perf'] = pickle.load(f)

    # BERT opsiyonel (GPU gerektiriyor)
    for key in ['bert_A_state','bert_B_state','bert_C_state']:
        p = SAVE_DIR / f"{key}.pkl"
        if p.exists():
            try:
                models[key] = torch.load(
                    p,
                    map_location=torch.device('cpu'),
                    weights_only=False
                )
            except Exception as e:
                print(f"⚠️ {key} yüklenemedi, atlanıyor: {e}")
                models[key] = None

    return models, []


def predict_classic(model, vectorizer, text: str, algo: str) -> tuple:
    """MNB veya XGB/LR için tahmin + olasılık döndürür."""
    from sklearn.preprocessing import normalize
    cleaned = clean_text(text)
    X = vectorizer.transform([cleaned])
    if algo == 'MNB':
        X = normalize(X, norm='l1')
    pred  = int(model.predict(X)[0])
    proba = model.predict_proba(X)[0]
    return pred, proba


def load_bert_model(state_dict, device='cpu'):
    """BERT modelini state_dict'ten yükler."""
    try:
        import torch
        from transformers import DistilBertConfig, DistilBertForSequenceClassification
        
        # from_pretrained yerine config'den sıfır ağırlıkla başla
        config = DistilBertConfig.from_pretrained(
            'distilbert-base-uncased',
            num_labels=2
        )
        model = DistilBertForSequenceClassification(config)
        
        # State dict'i yükle — strict=False yerine strict=True kullan
        missing, unexpected = model.load_state_dict(state_dict, strict=False)
        
        # Kritik katmanlar yüklendi mi kontrol et
        if 'classifier.weight' in missing:
            print(f"❌ classifier.weight yüklenemedi!")
            return None
            
        model.to(device)
        model.eval()
        return model
    except Exception as e:
        print(f"load_bert_model hatası: {e}")
        return None


def predict_bert(model, text: str) -> tuple:
    """BERT modeliyle tahmin yapar."""
    try:
        import torch
        from transformers import DistilBertTokenizerFast
        tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-uncased')
        cleaned = clean_text(text)
        enc = tokenizer([cleaned], truncation=True, padding=True,
                        max_length=256, return_tensors='pt')
        with torch.no_grad():
            out = model(**enc)
            proba = torch.softmax(out.logits, dim=1).numpy()[0]
        pred = int(proba.argmax())
        return pred, proba
    except Exception:
        return None, None


# Algoritma metadata
ALGO_META = {
    'MNB' : {'label': 'Multinomial Naive Bayes', 'color': '#4C9BE8', 'icon': '📊'},
    'XGB' : {'label': 'XGBoost + TF-IDF',        'color': '#FF9F1C', 'icon': '🌳'},
    'BERT': {'label': 'DistilBERT (Transformer)', 'color': '#9B59B6', 'icon': '🤖'},
}

SCENARIO_LABELS = {
    'A→DS1'    : 'Model A — Train:DS1 / Test:DS1',
    'A→DS2'    : 'Model A — Train:DS1 / Test:DS2 (cross)',
    'B→DS2'    : 'Model B — Train:DS2 / Test:DS2',
    'B→DS1'    : 'Model B — Train:DS2 / Test:DS1 (cross)',
    'C→DS1+DS2': 'Model C — Train:DS1+DS2 / Test:Mixed',
}
